{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-uwot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/uwot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/uwot/uwot_{{ version }}.tar.gz
  sha256: d9938c43d29530d4b36d1b2649cc679b09945a740db2cd3a266242b1aa9a6cd1

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-fnn                      # [build_platform != target_platform]
    - r-rcppprogress             # [build_platform != target_platform]
    - r-dqrng                    # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-irlba                    # [build_platform != target_platform]
    - r-rcppannoy                # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-fnn
    - r-matrix
    - r-rcpp
    - r-rcppannoy >=0.0.17
    - r-rcppprogress
    - r-dqrng
    - r-irlba
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-fnn
    - r-matrix
    - r-rcpp
    - r-rcppannoy >=0.0.17
    - r-rcppprogress
    - r-dqrng
    - r-irlba

test:
  commands:
    - $R -e "library('uwot')"           # [not win]
    - "\"%R%\" -e \"library('uwot')\""  # [win]

about:
  home: https://github.com/jlmelville/uwot
  license: GPL-3.0-or-later
  summary: "An implementation of the Uniform Manifold Approximation and Projection dimensionality reduction by McInnes et al. (2018) <arXiv:1802.03426>. It also provides means to transform new data and to carry out supervised dimensionality reduction. An implementation of the related LargeVis method of Tang et al. (2016)
    <arXiv:1602.00370> is also provided. This is a complete re-implementation in R (and C++, via the 'Rcpp' package): no Python installation is required. See the uwot website (<https://github.com/jlmelville/uwot>) for more documentation and examples."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: uwot
# Title: The Uniform Manifold Approximation and Projection (UMAP) Method for Dimensionality Reduction
# Version: 0.1.5
# Authors@R: c(person("James", "Melville", email = "jlmelville@gmail.com", role = c("aut", "cre")), person("Aaron", "Lun", role="ctb"),person("Mohamed Nadhir", "Djekidel", role="ctb"))
# Description: An implementation of the Uniform Manifold Approximation and Projection dimensionality reduction by McInnes et al. (2018) <arXiv:1802.03426>. It also provides means to transform new data and to carry out supervised dimensionality reduction. An implementation of the related LargeVis method of Tang et al. (2016) <arXiv:1602.00370> is also provided. This is a complete re-implementation in R (and C++, via the 'Rcpp' package): no Python installation is required. See the uwot website (<https://github.com/jlmelville/uwot>) for more documentation and examples.
# License: GPL-3
# URL: https://github.com/jlmelville/uwot
# BugReports: https://github.com/jlmelville/uwot/issues
# Encoding: UTF-8
# LazyData: true
# Suggests: testthat, covr
# RoxygenNote: 7.0.2
# Depends: Matrix
# LinkingTo: Rcpp, RcppProgress, RcppParallel, RcppAnnoy, dqrng
# Imports: Rcpp, methods, FNN, RSpectra, RcppAnnoy (>= 0.0.11), RcppParallel, irlba
# SystemRequirements: GNU make
# NeedsCompilation: yes
# Packaged: 2019-12-04 08:05:20 UTC; jlmel
# Author: James Melville [aut, cre], Aaron Lun [ctb], Mohamed Nadhir Djekidel [ctb]
# Maintainer: James Melville <jlmelville@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-12-04 16:20:02 UTC
