appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: L4DTaqUxXauAc2TgY52iZjWFHSsoKQ7ZYj1eB7CP+JXy1vNkHYcHfk1ahcVHmkrkfdDupaZmAVbxdDgRWD+qQMyzfOKLgX8GZZum3cqOLXknZm/zwgtTmL7vW6lKC2hHd+aMuWtbRlMy3Vp8UP6mg0SldYCnJquyzpul5R+sQFobhB7PsJGvNj/2OlYaxK+QCxySOvacjYccvVVkoK4h+TgdoYgGzQ9+twDcCibLOpN5ClJtxr1/3LuxLC2arTKFMRX2qcW/mZqAkKmSIK3NTsjxFXPeN0dlAp6uo7OdnOxBJ54qWuWKahqIBj0Vl2PIj3YxxELZ8Dl8HJxHPpxm7Kt/DtVzQm1iJxEwIWq0hkdNs9NOpmSPFxDawrWOWrSXt2HJWmfW8YfXg2viTuqNK/KPEp5f4TlWjwhbfJcVv2Ms8mLEhozteIKAq1BKJsIDIWVKDp8juQuyTFeYu5N3J4YSrm32+7ACMY9JorRcfAW//n5SRrhw78vV3Tf68mxH4jkmQoQjXhgeA1LCsnq3VbgTMFRE7/4wZ20nL8yTgoFJevcK6jRJFTBM1RxQ0LJnAA8bmr3ufKmrtvi8qwnALvCBw9/0C6nlc1hLJvDf1LK8wSuYJllE+Y/1PStaS+e4sQJmTpmUCGxucMp2DKvQU26GawoCGC5O7U5eFsB8z1A=
conda_forge_output_validation: false
